jobs:
  pr:
    permissions: write-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: OpenGamma/OGBot@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
name: ogbot
on:
  repository_dispatch:
    types: trigger-ga___ogbot.yml
